### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CyphasCaynSpartac** [ceresward/factorio-logiNetChannels#3]
When opening power armor i get an error.
i am running other mods, including Mega Bot Start mod 
![20191213163433_1](https://user-images.githubusercontent.com/23236791/70771917-f63acc00-1dc6-11ea-9b5c-8de80da073e9.jpg)

**Comment by ceresward** [comment]
Can you please check if you are running the latest version (1.0.5)?  I pushed it out just today, it should fix this issue.

**Comment by kpande** [comment]
also had a game breaking crash and needed to remove the mod, but i don't have a backtrace. i will try and reproduce it sometime.

**Comment by kpande** [comment]
my issue is resolved, thank you.
